<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>C端h5接口自动化测试</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.test_case   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">C端h5接口自动化测试</h1>
<p class='attribute'><strong>测试人员 : </strong> 唐阳辉</p>
<p class='attribute'><strong>开始时间 : </strong> 2021-08-23 11:21:18</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:12.023109</p>
<p class='attribute'><strong>测试结果 : </strong> 共 31，错误 31，通过率= 0.00%</p>

<p class='description'>此次测试了31个接口</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 31 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>test_find_community.MyTestCase</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">4</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',4)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_community_1_找社区banner_口腔频道_品牌数据接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_community.py", line 37, in test_find_community
    Handler.Excle.write_excle(Form="find_community", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_community_2_找社区人气优先列表</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_community.py", line 37, in test_find_community
    Handler.Excle.write_excle(Form="find_community", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_community_3_找社区距离优先列表</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_community.py", line 37, in test_find_community
    Handler.Excle.write_excle(Form="find_community", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_community_4_找社区好评优先列表</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_community.py", line 37, in test_find_community
    Handler.Excle.write_excle(Form="find_community", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_find_doctor.MyTestCase</td>
    <td class="text-center">5</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',5)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_doctor_1_固定科室接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_doctor.py", line 37, in test_find_doctor
    Handler.Excle.write_excle(Form="find_doctor", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_doctor_2_找医生接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_doctor.py", line 37, in test_find_doctor
    Handler.Excle.write_excle(Form="find_doctor", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_doctor_3_找名医banner</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_doctor.py", line 37, in test_find_doctor
    Handler.Excle.write_excle(Form="find_doctor", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_doctor_4_找名医科室标签接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_doctor.py", line 37, in test_find_doctor
    Handler.Excle.write_excle(Form="find_doctor", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='test_case'>test_find_doctor_5_找名医全部科室接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_find_doctor.py", line 37, in test_find_doctor
    Handler.Excle.write_excle(Form="find_doctor", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_message.MyTestCase</td>
    <td class="text-center">5</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',5)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_1_我的消息数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_message.py", line 49, in test_projects
    Handler.Excle.write_excle(Form="my_message", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_2_运营消息</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_message.py", line 49, in test_projects
    Handler.Excle.write_excle(Form="my_message", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_3_服务通知</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_message.py", line 49, in test_projects
    Handler.Excle.write_excle(Form="my_message", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_4_订阅通知</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_message.py", line 49, in test_projects
    Handler.Excle.write_excle(Form="my_message", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_5_系统通知</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_message.py", line 49, in test_projects
    Handler.Excle.write_excle(Form="my_message", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_my.MyTestCase</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',7)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_1_我的咨询</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_2_我的预约</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse in" align="left">
    <pre>
    
ft4_2: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_3_我的医生</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_4' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_4_我的社区</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_4'>错误</button>
    <div id='div_ft4_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_4'>错误</button>
    <div id='div_ft4_4' class="collapse in" align="left">
    <pre>
    
ft4_4: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_5' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_5_我的收藏</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_5'>错误</button>
    <div id='div_ft4_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_5'>错误</button>
    <div id='div_ft4_5' class="collapse in" align="left">
    <pre>
    
ft4_5: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_6' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_6_我的就诊人管理</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_6'>错误</button>
    <div id='div_ft4_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_6'>错误</button>
    <div id='div_ft4_6' class="collapse in" align="left">
    <pre>
    
ft4_6: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_7' class='none'>
    <td class='errorCase'><div class='test_case'>test_projects_7_我的消息数</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_7'>错误</button>
    <div id='div_ft4_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_7'>错误</button>
    <div id='div_ft4_7' class="collapse in" align="left">
    <pre>
    
ft4_7: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_my.py", line 54, in test_projects
    Handler.Excle.write_excle(Form="test_my", row=case_info["case_id"] + 1, column=10, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_pagehome.MyTestCase</td>
    <td class="text-center">10</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">10</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',10)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='ft5_1' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_01_首页关注</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse in" align="left">
    <pre>
    
ft5_1: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_2' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_02_首页咨询案例列表</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse in" align="left">
    <pre>
    
ft5_2: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_3' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_03_首页诊间日记文章列表</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse in" align="left">
    <pre>
    
ft5_3: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_4' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_04_首页病例分析文章列表接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_4'>错误</button>
    <div id='div_ft5_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_4'>错误</button>
    <div id='div_ft5_4' class="collapse in" align="left">
    <pre>
    
ft5_4: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_5' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_05_首页订阅文章列表接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_5'>错误</button>
    <div id='div_ft5_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_5'>错误</button>
    <div id='div_ft5_5' class="collapse in" align="left">
    <pre>
    
ft5_5: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_6' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_06_首页健康科普文章列表接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_6'>错误</button>
    <div id='div_ft5_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_6'>错误</button>
    <div id='div_ft5_6' class="collapse in" align="left">
    <pre>
    
ft5_6: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_7' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_07_首页最新活动接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_7'>错误</button>
    <div id='div_ft5_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_7'>错误</button>
    <div id='div_ft5_7' class="collapse in" align="left">
    <pre>
    
ft5_7: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_8' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_08_首页科室</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_8'>错误</button>
    <div id='div_ft5_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_8'>错误</button>
    <div id='div_ft5_8' class="collapse in" align="left">
    <pre>
    
ft5_8: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_9' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_09_首页banner</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_9'>错误</button>
    <div id='div_ft5_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_9'>错误</button>
    <div id='div_ft5_9' class="collapse in" align="left">
    <pre>
    
ft5_9: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_10' class='none'>
    <td class='errorCase'><div class='test_case'>test_follow_10_搜索接口</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_10'>错误</button>
    <div id='div_ft5_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_10'>错误</button>
    <div id='div_ft5_10' class="collapse in" align="left">
    <pre>
    
ft5_10: Traceback (most recent call last):
  File "D:\新建文件夹\lib\site-packages\ddt.py", line 188, in wrapper
    return func(self, *args, **kwargs)
  File "D:\接口自动化\testcase\test_pagehome.py", line 40, in test_follow
    Handler.Excle.write_excle(Form="home_page", row=case_info["case_id"] + 1, column=9, data="pass")
  File "D:\接口自动化\common\Excel.py", line 37, in write_excle
    self.save_excle()
  File "D:\接口自动化\common\Excel.py", line 41, in save_excle
    self.workbook.save(self.file_name)
  File "D:\新建文件夹\lib\site-packages\openpyxl\workbook\workbook.py", line 392, in save
    save_workbook(self, filename)
  File "D:\新建文件夹\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\新建文件夹\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'D:\\接口自动化\\data\\test_cases.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>31</td>
    <td>0</td>
    <td>0</td>
    <td>31</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
